sudo: false

addons:
  apt:
    packages:
    - libgmp-dev

cache:
  directories:
  - $HOME/.stack

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - travis_wait stack --stack-yaml stack-travis.yaml --skip-ghc-check setup

script:
  - travis_wait stack --stack-yaml stack-travis.yaml --skip-ghc-check build
